all: server client

server: server.o
	gcc -pthread server.o -o server

server.o:
	gcc -c server.c


client: client.o
	gcc -pthread client.o -o client -lncurses

client.o:
	gcc -c client.c

clear:
	rm -rf *.o server client
